/// 内部命令信息
pub struct InternalCommandInfo {
    pub name: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub english_name: &'static str,
    pub keywords: &'static [&'static str],
    pub icon: &'static str,
    pub requires_confirmation: bool,
}

/// 所有内部页面命令列表
pub static INTERNAL_COMMANDS: &[InternalCommandInfo] = &[
    InternalCommandInfo {
        name: "open_settings",
        title: "设置",
        description: "打开 Onin 设置",
        english_name: "Settings",
        keywords: &["设置"],
        icon: "gear",
        requires_confirmation: false,
    },
    InternalCommandInfo {
        name: "open_settings_general",
        title: "通用设置",
        description: "打开 Onin 通用设置项",
        english_name: "General Settings",
        keywords: &["通用设置"],
        icon: "gear",
        requires_confirmation: false,
    },
    InternalCommandInfo {
        name: "open_settings_startup",
        title: "文件启动",
        description: "打开 Onin 文件启动设置项",
        english_name: "Startup Settings",
        keywords: &["文件启动"],
        icon: "rocketLaunch",
        requires_confirmation: false,
    },
    InternalCommandInfo {
        name: "open_settings_commands",
        title: "指令设置",
        description: "打开 Onin 指令管理设置项",
        english_name: "Command Settings",
        keywords: &["指令设置"],
        icon: "terminalWindow",
        requires_confirmation: false,
    },
    InternalCommandInfo {
        name: "open_settings_extensions",
        title: "扩展",
        description: "打开 Onin 扩展与插件设置项",
        english_name: "Extension Settings",
        keywords: &["扩展"],
        icon: "puzzlePiece",
        requires_confirmation: false,
    },
    InternalCommandInfo {
        name: "open_settings_shortcuts",
        title: "全局快捷键",
        description: "打开 Onin 全局快捷键设置项",
        english_name: "Shortcut Settings",
        keywords: &["全局快捷键"],
        icon: "keyboard",
        requires_confirmation: false,
    },
    InternalCommandInfo {
        name: "open_settings_ai",
        title: "AI 能力",
        description: "打开 Onin AI 能力配置项",
        english_name: "AI Settings",
        keywords: &["AI 能力"],
        icon: "sparkle",
        requires_confirmation: false,
    },
    InternalCommandInfo {
        name: "open_settings_sync",
        title: "数据同步",
        description: "打开 Onin 数据同步配置项",
        english_name: "Sync Settings",
        keywords: &["数据同步"],
        icon: "cloud",
        requires_confirmation: false,
    },
    InternalCommandInfo {
        name: "open_settings_my_data",
        title: "我的数据",
        description: "打开 Onin 个人数据管理",
        english_name: "My Data Settings",
        keywords: &["我的数据"],
        icon: "database",
        requires_confirmation: false,
    },
    InternalCommandInfo {
        name: "open_plugins_manager",
        title: "插件管理",
        description: "管理 Onin 的各类插件",
        english_name: "Plugin Manager",
        keywords: &["插件管理"],
        icon: "plugsConnected",
        requires_confirmation: false,
    },
];
